build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  amd64: ghcr.io/home-assistant/amd64-base:3.19
args:
  NODEJS_VERSION: 22
labels:
  org.opencontainers.image.title: "OpenClaw"
  org.opencontainers.image.description: "OpenClaw.ai personal AI assistant"
  org.opencontainers.image.source: "https://github.com/openclaw/openclaw"
  org.opencontainers.image.licenses: "MIT"
