build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
labels:
  org.opencontainers.image.title: "OpenClaw"
  org.opencontainers.image.description: "OpenClaw.ai personal AI assistant"
  org.opencontainers.image.source: "https://github.com/openclaw/openclaw"
  org.opencontainers.image.licenses: "MIT"
